### ISSUE TITLE
Handle `null` return values from Motoko canisters

### ISSUE THREAD

**Issue by dansteren** [jorgenbuilder/chrome-ic-inspector#23]
**Description**
When making a query to a motoko canister that returns a `null` value, the decoder doesn't capture the event.

**To Reproduce**

1. Deploy (locally) the following motoko canister:
```motoko
actor HelloWorld {
  public query func getNull(): async Null {
    return null;
  };
}
```
2. Open the candid UI website for your deployed canister. Likely at http://ryjl3-tyaaa-aaaaa-aaaba-cai.localhost:8000/?id=rrkah-fqaaa-aaaaa-aaaaq-cai
3. Click "Query" to make a query to the canister
![image](https://user-images.githubusercontent.com/5455419/172727515-387ef95a-e919-4217-9d1b-364cf0f8165b.png)
4. Note that the canister call is made successfully (as shown in the Candid UI), but the event isn't captured by the decoder.

**Expected behavior**
The call should be captured by the decoder, show up in the decoder panel, and correctly display that the returned data is `null`.

**System Information**

- OS: Ubuntu 21.10
- Browser: Brave Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)

**Additional context**
This only seems to be a problem with Motoko canisters. I've deployed the equivalent canister in Rust and [Azle](https://github.com/demergent-labs/azle) and the decoder can handle those responses fine.

The candid of the deployed canister is:

```candid
service : {
  getNull: () -> (null) query;
}
```

**Comment by jorgenbuilder** [comment]
Thanks so much for the report! I will attempt a repro + fix later today.

**Comment by jorgenbuilder** [comment]
Tidying up, this was fixed in a previous release.
