### ISSUE TITLE
Publish Request - Firefox

### ISSUE THREAD

**Issue by MrWoo034** [jorgenbuilder/chrome-ic-inspector#31]
[It looks like](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension) Mozilla generally supports cross compilation of Chrome extensions for Firefox.  Is it possible to get builds of this extension published for Firefox?

**Comment by jorgenbuilder** [comment]
Hey MrWoo, sorry for the late response! Firefox is release manifest v3 support in Firefox version 109, set to release on the 17th of this month (January 2023). I have already submitted the extension to their addon store for review. Hopefully we'll be in firefox soon :)

**Comment by jorgenbuilder** [comment]
I've just tested the extension in Firefox Nightly and it everything seems functional. :) Some UI tweaks will make it fit firefox a bit better, but for basic use we should be ready to go very soon. If you want to try this out now you can:

1. get firefox nightly at nightly.firefox.com
2. download the latest build of ic inspector: https://github.com/jorgenbuilder/ic-inspector/releases/tag/v1.1.1
3. go to `about:debugging`, select `load temporary addon`, and select the zip downloaded in previous step

![image](https://user-images.githubusercontent.com/60938577/211164468-14155471-a100-4129-b724-44420c2f1c7c.png)

**Comment by jorgenbuilder** [comment]
Closing this issue! Firefox 109 was release today, and we are now listed with Firefox addons. Basic functionality appears good, but some more testing will be in order this week.
